#!/usr/bin/env python3
"""Insert the geotagged Branford production/application photo galleries into
the four product hubs, /about/ and /solutions/, and register every photo in
sitemap.xml as an image entry.

Idempotent: the gallery HTML lives between <!-- PHOTOS:START/END --> and the
CSS between /* PHOTOS:START */ ... /* PHOTOS:END */; re-running replaces both.
Source images: googleposts new/autac gbp/web/*.webp (1200px, IPTC/XMP/GPS
metadata intact). Copy them to images/ before running.
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
IMG = ROOT / "images"

# alt text is the photo's XMP title minus the trailing brand/location suffix
# where that would read as keyword stuffing; captions carry Branford.
PAGES = {
  "retractile-cords/index.html": dict(
    anchor='    <section class="category-section" id="tpe-power">',
    label="From Our Production Floor",
    title="Retractile Cords Made in Branford, Connecticut",
    desc="Every retractile cord we ship is wound, heat set, and inspected at 25 Thompson Rd. A few from recent runs:",
    photos=[
      ("coiled-battery-cable-red-black-winding-mandrel-branford-ct.webp", "Heavy gauge red and black coiled battery cable on a winding mandrel", "Heavy gauge battery cable coming off the winding mandrel"),
      ("retractile-cords-multiple-colors-branford-ct.webp", "Retractile coil cords in white, red, black, yellow, gray, and green jackets", "Stock and custom jacket colors"),
      ("spiral-cable-stretched-coiled-cord-branford-ct.webp", "Black retractile cord stretched to its full extended length", "Retracted to extended: 1:5 ratio standard"),
      ("retractile-power-cord-black-coiled-branford-ct.webp", "Black retractile power cord in its retracted coiled state", "Retracted and ready to ship"),
    ]),
  "coiled-cords/index.html": dict(
    anchor='  <!-- PRODUCT SECTIONS (generated by scripts/build-hub-tables.py - do not hand-edit) -->',
    label="From Our Production Floor",
    title="Coiled Cords in Production, Branford, Connecticut",
    desc="Custom colors, custom lengths, and small coiled parts all come off the same racks at our Branford plant.",
    photos=[
      ("custom-green-coiled-cables-production-rack-branford-ct.webp", "Rack of custom green coiled cables wound on mandrels", "A custom green production run on the rack"),
      ("coiled-cords-red-white-blue-on-mandrels-branford-ct.webp", "Red, white, and blue striped coiled cords on winding mandrels", "Striped jackets, racked before heat set"),
      ("custom-yellow-coiled-cords-finished-batch-branford-ct.webp", "Finished batch of yellow coiled cords bundled on the bench", "A finished high visibility yellow batch"),
      ("red-coiled-safety-lanyard-cord-with-clip-branford-ct.webp", "Red coiled safety lanyard cord with molded clip", "Small coiled parts: a kill switch lanyard"),
    ]),
  "curly-cords/index.html": dict(
    anchor='  <!-- PRODUCT SECTIONS (generated by scripts/build-hub-tables.py - do not hand-edit) -->',
    label="Curly Cords in the Field",
    title="Curly Cords Made in Branford, Connecticut",
    desc="Curly cords go wherever a moving part needs power or signal. A few applications and builds from our Branford plant:",
    photos=[
      ("curly-cords-claw-crane-arcade-machine-branford-ct.webp", "Black curly cords feeding the claw mechanism of an arcade crane game", "Powering the claw on an arcade crane game"),
      ("spiral-cable-black-coiled-cord-branford-ct.webp", "Black matte jacket curly coiled cord", "Matte black jacket, tight coil"),
      ("custom-retractile-gray-coiled-cable-branford-ct.webp", "Gray curly coiled cable with modular connector", "Gray jacket with modular connector"),
      ("spiral-cable-conductor-cross-section-branford-ct.webp", "Cut end of a coiled cable showing multi-conductor construction", "Multi-conductor construction, cut end"),
    ]),
  "cord-sets/index.html": dict(
    anchor='  <section class="specs-section">',
    label="Cord Sets on Real Equipment",
    title="Autac Cord Sets in the Field",
    desc="Terminated, strain relieved, and installed on the equipment they were built for. All manufactured in Branford, Connecticut.",
    photos=[
      ("coiled-power-cord-portable-led-work-light-branford-ct.webp", "Black coiled power cord with twist-lock plug on a portable LED scene light", "Coiled power cord on a portable LED scene light"),
      ("coiled-extension-cord-tripod-led-light-stand-branford-ct.webp", "Black coiled extension cord on a telescoping tripod LED light", "Coiled extension cord on a tripod light stand"),
      ("retractile-cord-emergency-vehicle-branford-ct.webp", "Gray retractile cord in use on emergency vehicle equipment", "Retractile cord on emergency vehicle equipment"),
      ("curly-power-cord-black-three-prong-plug-branford-ct.webp", "Black curly power cord with molded three-prong plug", "Molded three-prong plug on a curly power cord"),
    ]),
  "about/index.html": dict(
    anchor='  <!-- EXPERIENCE -->',
    label="Inside the Plant",
    title="25 Thompson Road, Branford, Connecticut",
    desc="Every cord we sell is made by our own team, in our own building, in the same Connecticut town where the company has operated for decades.",
    photos=[
      ("yellow-coiled-cords-manufacturing-rack-technician-branford-ct.webp", "Autac technician racking yellow coiled cords on mandrels for heat setting", "Racking coiled cords before heat set"),
      ("cooling-department-equipment-fresh-paint-branford-ct.webp", "Freshly painted cooling department equipment on the Autac manufacturing floor", "The cooling department, freshly repainted"),
      ("autac-usa-trade-show-booth-retractile-cords-branford-ct.webp", "Autac USA trade show booth showing retractile cords for medical, communication, transportation, and military industries", "Our booth: medical, communication, transportation, military"),
      ("autac-usa-facility-exterior-branford-ct.webp", "Exterior of the Autac USA manufacturing facility in Branford, Connecticut", "The Autac USA plant at 25 Thompson Rd"),
    ]),
  "solutions/index.html": dict(
    anchor='  <section class="build-cord">',
    label="In the Field",
    title="Autac Cords on the Job",
    desc="Retractile cords and cord sets built in Branford, Connecticut, installed on the equipment our customers make.",
    photos=[
      ("retractile-cord-emergency-vehicle-branford-ct.webp", "Gray retractile cord in use on emergency vehicle equipment", "Transportation and public safety: emergency vehicle equipment"),
      ("coiled-power-cord-portable-led-work-light-branford-ct.webp", "Black coiled power cord with twist-lock plug on a portable LED scene light", "Electrical: portable LED scene lighting"),
      ("coiled-extension-cord-tripod-led-light-stand-branford-ct.webp", "Black coiled extension cord on a telescoping tripod LED light", "Utility: tripod mast lighting"),
    ]),
}

CSS = """    /* PHOTOS:START */
    .photo-gallery { padding: 4rem 0; background: var(--white); }
    .photo-gallery .section-desc { max-width: 720px; color: var(--text-light); }
    .photo-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 1.25rem; margin-top: 2rem; }
    .photo-grid figure { margin: 0; border-radius: 0.75rem; overflow: hidden; background: var(--gray-100); border: 1px solid var(--gray-200); }
    .photo-grid img { display: block; width: 100%; height: auto; aspect-ratio: 4 / 3; object-fit: cover; }
    .photo-grid figcaption { font-size: 0.85rem; color: var(--text-light); padding: 0.75rem 1rem; line-height: 1.4; }
    /* PHOTOS:END */
"""

def dims(name):
    # read WebP VP8/VP8L/VP8X dimensions without PIL
    b = (IMG / name).read_bytes()
    chunk = b[12:16]
    if chunk == b"VP8X":
        w = int.from_bytes(b[24:27], "little") + 1; h = int.from_bytes(b[27:30], "little") + 1
    elif chunk == b"VP8L":
        bits = int.from_bytes(b[21:25], "little")
        w = (bits & 0x3FFF) + 1; h = ((bits >> 14) & 0x3FFF) + 1
    else:  # VP8
        w = int.from_bytes(b[26:28], "little") & 0x3FFF; h = int.from_bytes(b[28:30], "little") & 0x3FFF
    return w, h

def gallery(cfg):
    figs = []
    for name, alt, cap in cfg["photos"]:
        w, h = dims(name)
        figs.append(f'''        <figure>
          <img src="/images/{name}" alt="{alt}" width="{w}" height="{h}" loading="lazy" decoding="async">
          <figcaption>{cap}</figcaption>
        </figure>''')
    return f'''  <!-- PHOTOS:START -->
  <section class="photo-gallery" aria-labelledby="photo-gallery-title">
    <div class="container">
      <div class="section-label">{cfg["label"]}</div>
      <h2 class="section-title" id="photo-gallery-title">{cfg["title"]}</h2>
      <p class="section-desc">{cfg["desc"]}</p>
      <div class="photo-grid">
{chr(10).join(figs)}
      </div>
    </div>
  </section>
  <!-- PHOTOS:END -->

'''

check = "--check" in sys.argv
stale = 0
for rel, cfg in PAGES.items():
    p = ROOT / rel
    src = p.read_text()
    new = src
    # CSS
    new = re.sub(r"    /\* PHOTOS:START \*/.*?/\* PHOTOS:END \*/\n", "", new, flags=re.S)
    assert new.count("  </style>") == 1, rel
    new = new.replace("  </style>", CSS + "  </style>", 1)
    # HTML
    new = re.sub(r"  <!-- PHOTOS:START -->.*?<!-- PHOTOS:END -->\n\n", "", new, flags=re.S)
    assert new.count(cfg["anchor"] + "\n") == 1, (rel, "anchor")
    new = new.replace(cfg["anchor"] + "\n", gallery(cfg) + cfg["anchor"] + "\n", 1)
    if new != src:
        stale += 1
        if not check:
            p.write_text(new); print("PHOTOS OK:", rel)
        else:
            print("STALE:", rel)

# ---- sitemap image entries ----
sm = ROOT / "sitemap.xml"
s = sm.read_text()
if 'xmlns:image=' not in s:
    s = s.replace('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
                  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">')
s2 = s
for rel, cfg in PAGES.items():
    loc = "https://autacusa.com/" + rel.replace("index.html", "")
    imgs = "".join(f"    <image:image>\n      <image:loc>https://autacusa.com/images/{n}</image:loc>\n      <image:title>{alt}</image:title>\n    </image:image>\n" for n, alt, _ in cfg["photos"])
    pat = re.compile(r"(  <url>\n    <loc>" + re.escape(loc) + r"</loc>\n(?:(?!  </url>).)*?)(?:    <image:image>.*?</image:image>\n)*(  </url>)", re.S)
    s2, n = pat.subn(lambda m: m.group(1) + imgs + m.group(2), s2, count=1)
    assert n == 1, (rel, "sitemap url not found")
if s2 != sm.read_text():
    stale += 1
    if not check: sm.write_text(s2); print("SITEMAP OK")
    else: print("STALE: sitemap.xml")

if check:
    sys.exit(1 if stale else 0)
print("=== done ===")
